common: &common
  access_key_id: AKIAIWWQF5REKTC4ZYGQ
 secret_access_key: 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

development:
   <<: *common
   bucket: anushrees1



test:
   <<: *common
   bucket: anushrees1



production:
   <<: *common
   bucket: anushrees1

